// Hand-written smoke DUT for the simharness bus contract: write/readback RAM,
// print "Hi\n" over the UART, then report pass/fail via the HTIF tohost word.
// Not generated by Kathryn — this exists only to validate the harness itself.

module smoke(
    input  wire        clk,
    input  wire        mrst,
    output reg         mem_req,
    output reg         mem_we,
    output reg  [63:0] mem_addr,
    output reg  [63:0] mem_wdata,
    output reg  [1:0]  mem_size,
    input  wire        mem_ack,
    input  wire [63:0] mem_rdata,
    input  wire        mtip,
    input  wire        msip,
    input  wire        meip
);

    localparam RAM_SCRATCH = 64'h8000_0100;
    localparam UART_BASE   = 64'h1000_0000;
    localparam TOHOST      = 64'h8000_1000;
    localparam MAGIC       = 64'hDEAD_BEEF_CAFE_F00D;

    reg [3:0]  step;
    reg [63:0] readback;

    always @(posedge clk) begin
        if (mrst) begin
            step     <= 0;
            mem_req  <= 0;
            mem_we   <= 0;
            mem_addr <= 0;
            mem_wdata<= 0;
            mem_size <= 0;
            readback <= 0;
        end else if (mem_req && mem_ack) begin
            if (step == 1) readback <= mem_rdata;
            mem_req <= 0;
            step    <= step + 1;
        end else if (!mem_req && step <= 5) begin
            mem_req <= 1;
            case (step)
                0: begin mem_we <= 1; mem_addr <= RAM_SCRATCH; mem_wdata <= MAGIC;  mem_size <= 3; end
                1: begin mem_we <= 0; mem_addr <= RAM_SCRATCH;                      mem_size <= 3; end
                2: begin mem_we <= 1; mem_addr <= UART_BASE;   mem_wdata <= 64'h48; mem_size <= 0; end // 'H'
                3: begin mem_we <= 1; mem_addr <= UART_BASE;   mem_wdata <= 64'h69; mem_size <= 0; end // 'i'
                4: begin mem_we <= 1; mem_addr <= UART_BASE;   mem_wdata <= 64'h0A; mem_size <= 0; end // '\n'
                5: begin
                    mem_we    <= 1;
                    mem_addr  <= TOHOST;
                    mem_wdata <= (readback == MAGIC) ? 64'd1 : 64'd5;   // pass : fail(2)
                    mem_size  <= 3;
                end
                default: mem_req <= 0;
            endcase
        end
    end

endmodule
